import catchAsyncError from "../utils/captureAsyncError";

/**
 * Create a tash
 * Route - /create-task
 */
const createTask = catchAsyncError(async (req, res, next) => {});
